[package]
name = "ultra-controllers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw20 = { version = "0.14.0" }
cosmwasm-std = { version = "1.0", features = ["iterator"] }
schemars = "0.8"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
uint = "0.9"
cw-storage-plus = {version = "0.14.0", features = ['iterator', 'macro']}
thiserror = "1.0.32"

[dev-dependencies]
cosmwasm-schema = "1.0"